export const promptList = [
  "A friendly dragon reading a book",
  "Astronauts playing with space dogs",
  "Underwater castle with mermaids",
  "Dinosaurs having a tea party",
  "Robots playing in a playground",
  "A treehouse in a magical forest",
  "Unicorns sliding down a rainbow",
  "Pirates finding a treasure chest",
  "Fairies dancing around mushrooms",
  "Cats having a birthday party",
  "A castle in the clouds",
  "Aliens playing soccer",
  "Teddy bears having a picnic",
  "A train with animal passengers",
  "Butterflies around a flower garden",
  "Penguins building a snowman",
  "Monkeys swinging through the jungle",
  "A submarine exploring the ocean",
  "Wizards in a magic school",
  "Bunnies planting carrots",
  "A hot air balloon adventure",
  "Elephants at a water park",
  "Superheroes saving a kitten",
  "A candy village with gingerbread houses",
  "Dinosaurs playing hide and seek",
  "Owls having a midnight party",
  "A rocket ship to the moon",
  "Frogs jumping on lily pads",
  "Knights protecting a castle",
  "Pandas in a bamboo forest",
  "A magical carousel with fantasy creatures",
  "Foxes camping in the woods",
  "A farm with happy animals",
  "Dolphins jumping through waves",
  "A haunted house that's actually friendly",
  "Squirrels collecting acorns",
  "A winter wonderland with ice skating animals",
  "Giraffes at a tall tree restaurant",
  "A circus with animal performers",
  "Turtles racing in slow motion",
  "A fairy tale castle with a dragon friend",
  "Bees making honey in a giant flower",
  "A dinosaur theme park",
  "Puppies playing in a park",
  "A magical library with books that fly",
  "Monsters having a slumber party",
  "A safari adventure with friendly animals",
  "Snowmen having a winter Olympics",
  "A garden with giant vegetables",
  "Kittens playing with yarn balls",
]
